Sprint 2
ClevertecFrontendLab/Nozeil pull request #2
Opened 2024-02-24 11:21 UTC by Nozeil

2024-02-24 15:37 UTC, Ivan6813 approved these changes

2024-02-25 10:21 UTC, byshlata requested changes
замечания по коду

2024-02-25 10:21 UTC, byshlata commented on src/components/auth-page/auth-forms/auth-forms.types.ts
> +export type OnFinishAuth = (
либо типы, либо интерфейсы

2024-02-25 10:21 UTC, byshlata commented on src/components/auth-page/auth-forms/login-form/password-options/password-options.module.css
> +        font-size: 14px;
все переменныеЖ зазмеры шрифтов, padding, margin  в отдельный файл и прокидывать в css,  а не повторять

2024-02-25 10:21 UTC, byshlata commented on src/components/auth-page/auth-page-content/auth-page-content.tsx
> +export default AuthPageContent;
импорты по default убираем

2024-02-25 10:21 UTC, byshlata commented on src/components/auth-page/auth-page.types.ts
> +    (typeof RESULT_CARD_TYPE_KEYS)[keyof typeof RESULT_CARD_TYPE_KEYS];
вот это прям отлично! Но нужно выбрать что-то одно, интерфейсы или типы

2024-02-25 10:21 UTC, byshlata commented on src/components/auth-page/confirm-email/confirm-email.tsx
> +export default ConfirmEmail;
по дефолту убираем

2024-02-25 10:21 UTC, byshlata commented on src/components/auth-page/input-group/input-group.tsx
> +const InputGroup = ({ children, type, mobileBreakpoint }: InputGroupProps) => {
const InputGroup: FC<InputGroupProps> = ({ children, type, mobileBreakpoint }) можешь вот так поправить

2024-02-25 10:46 UTC, Nozeil commented on src/components/auth-page/auth-page-content/auth-page-content.tsx
> +export default AuthPageContent;
А чем плох export default?

2024-02-25 11:43 UTC, Nozeil commented on src/components/auth-page/input-group/input-group.tsx
> +const InputGroup = ({ children, type, mobileBreakpoint }: InputGroupProps) => {
FC не рекомендуют использовать вроде как, несмотря на его изменения https://www.totaltypescript.com/you-can-stop-hating-react-fc

2024-02-26 14:03 UTC, byshlata approved these changes

2024-02-26 14:04 UTC, merged